[tool.poetry]
name = "land-consumption"
version = "0.0.1"
description = "This is the land consumption indicator."
authors = ["Charles Hatfield <charles.hatfield@heigit.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11.5"
climatoology = { git = "ssh://git@gitlab.gistools.geog.uni-heidelberg.de:2022/climate-action/climatoology.git", rev = "5.0.0" }
pydantic = "^2.5.3"
pydantic-settings = "^2.1.0"
geojson-pydantic = "^1.0.1"
shapely = "^2.0.2"
pyyaml = "^6.0.1"
ohsome = "^0.3.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"
responses = "^0.24.1"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
